server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marc677/orderingsystem.git
          searchPaths: config
          username: 1730365225@qq.com
          password: 848089816aBgit
      label: master #仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/