server:
  port: 8040
spring:
  application:
    name: order
  datasource:
    name: orderingsystem
    url: jdbc:mysql://localhost:3306/orderingsystem?allowMultiQueries=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.southwind.entity